[package]
name = "scad-runtime"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
scad-bytecode = { version = "0.1.0", path = "../bytecode" }
tracing = "0.1.36"
