[package]
name = "integration-tests"
version = "0.0.0"
edition = "2021"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
scad-syntax = { version = "0.1.0", path = "../crates/syntax" }
walkdir = "2.3.2"
