[package]
name = "scad-interpreter"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rowan = "0.15.8"
scad-syntax = { version = "0.1.0", path = "../syntax" }
